// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vwbyituqwnlmwwkqhtux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YnlpdHVxd25sbXd3a3FodHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTk3NzMsImV4cCI6MjA1OTA3NTc3M30.Ot6UVe10RyMOeV8VXlkq9CKPRUdHqkyk4zjYE8BS97Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY
);
